#!/bin/bash
#
# Additionally for LF file manager to work properly intall the following:
# - pygmentize          : For syntax highlighting in files
# - bastar and 7z       : Compressed file preview
# - transmission-cli    : Bittorrent file preview
#
#
# Khongor Bayarsaikhan - 2019

printf "=== Starting bootstrap ===\n\n"

ORIGINAL_WORKING_DIR=$(pwd)
cd $HOME

system_type=$(uname -s)

OH_MY_ZSH_ROOT="$HOME/.oh-my-zsh"
OH_MY_ZSH_CUSTOM="$OH_MY_ZSH_ROOT/custom"
OH_MY_ZSH_PLUGINS="$OH_MY_ZSH_CUSTOM/plugins"

VIM_BUNDLE="$HOME/.vim/bundle"

confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

if [ ! -d "$VIM_BUNDLE" ]; then
    # Installing pathogen
    echo "- Installing pathogen..."
    mkdir -p $HOME/.vim/autoload $VIM_BUNDLE
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
else
    echo "- Pathogen already installed"
fi

if [ ! -d "$VIM_BUNDLE/nerdcommenter" ]; then
    # Installing NERD Commenter
    echo "- Installing NERD Commenter..."
    git clone https://github.com/scrooloose/nerdcommenter.git $VIM_BUNDLE/nerdcommenter
else
    echo "- NERD Commenter already installed"
fi

if [ "$system_type" = "Linux" ]; then
    # Install Oh-My-Zsh
    if [ ! -f "$OH_MY_ZSH_ROOT/oh-my-zsh.sh" ]; then
        echo "- Installing Oh My Zsh..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    else
    	echo "- Oh My Zsh already installed"
    fi

    # Install zsh-nvm
    if [ ! -d "$OH_MY_ZSH_PLUGINS/zsh-nvm" ]; then
        echo "- Installing zsh-nvm..."
        git clone https://github.com/lukechilds/zsh-nvm $OH_MY_ZSH_PLUGINS/zsh-nvm
    else
    	echo "- zsh-nvm already installed"
    fi

    # Install zsh-autosuggestions
    if [ ! -d "$OH_MY_ZSH_PLUGINS/zsh-autosuggestions" ]; then
        echo "- Installing zsh-autosuggestions..."
        git clone https://github.com/zsh-users/zsh-autosuggestions $OH_MY_ZSH_PLUGINS/zsh-autosuggestions
    else
    	echo "- zsh-autosuggestions already installed"
    fi

    # Install zsh-syntax-highlighting
    if [ ! -d "$OH_MY_ZSH_PLUGINS/zsh-syntax-highlighting" ]; then
        echo "- Installing zsh-syntax-highlighting..."
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $OH_MY_ZSH_PLUGINS/zsh-syntax-highlighting
    else
    	echo "- zsh-syntax-highlighting already installed"
    fi

    # Install powerlevel9k
    if [ ! -d "$OH_MY_ZSH_CUSTOM/themes/powerlevel9k" ]; then
        echo "- Installing powerlevel9k..."
    	git clone https://github.com/bhilburn/powerlevel9k.git $OH_MY_ZSH_CUSTOM/themes/powerlevel9k
    else
    	echo "- powerlevel9k already installed"
    fi

fi

if [ -f "$HOME/.config/yadm/files.gpg" ]; then
    confirm "Decrypt files? [y/n]" && {
        printf "\nDecrypting files...\n";
        yadm decrypt;
    }
fi

confirm "Change yadm URL to SSH? [y/n]" && {
    printf "\nUpdating the yadm repo origin URL\n";
    yadm remote set-url origin "thiosin:thiosin/dotfiles.git";
}

cd $ORIGINAL_WORKING_DIR

printf "\n=== Finished bootstrap ===\n"
