#!/bin/bash
#
# Khongor Bayarsaikhan - 2019

printf "=== Starting bootstrap ===\n\n"

ORIGINAL_WORKING_DIR=$(pwd)
cd $HOME

system_type=$(uname -s)

ZSH_ROOT="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$ZSH_ROOT/custom/plugins"

VIM_BUNDLE="$HOME/.vim/bundle"

if [ ! -d "$VIM_BUNDLE" ]; then
    # Installing pathogen
    echo "- Installing pathogen..."
    mkdir -p $HOME/.vim/autoload $VIM_BUNDLE
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
else
    echo "- Pathogen already installed"
fi

if [ ! -d "$VIM_BUNDLE/nerdcommenter" ]; then
    # Installing NERD Commenter
    echo "- Installing NERD Commenter..."
    git clone https://github.com/scrooloose/nerdcommenter.git $VIM_BUNDLE/nerdcommenter
else
    echo "- NERD Commenter already installed"
fi

if [ "$system_type" = "Linux" ]; then
    # Install Oh-My-Zsh
    if [ ! -d "$ZSH_ROOT" ]; then
        echo "- Installing Oh My Zsh..."
        curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    else
    	echo "- Oh My Zsh already installed"
    fi

    # Install zsh-nvm
    if [ ! -d "$ZSH_CUSTOM/zsh-nvm" ]; then
        echo "- Installing zsh-nvm..."
        git clone https://github.com/lukechilds/zsh-nvm $ZSH_CUSTOM/zsh-nvm
    else
    	echo "- zsh-nvm already installed"
    fi

    # Install zsh-autosuggestions
    if [ ! -d "$ZSH_CUSTOM/zsh-autosuggestions" ]; then
        echo "- Installing zsh-autosuggestions..."
        git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/zsh-autosuggestions
    else
    	echo "- zsh-autosuggestions already installed"
    fi

    # Install zsh-syntax-highlighting
    if [ ! -d "$ZSH_CUSTOM/zsh-syntax-highlighting" ]; then
        echo "- Installing zsh-syntax-highlighting..."
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/zsh-syntax-highlighting
    else
    	echo "- zsh-syntax-highlighting already installed"
    fi

    # Install powerlevel9k
    if [ ! -d "$ZSH_ROOT/custom/themes/powerlevel9k" ]; then
        echo "- Installing powerlevel9k..."
	git clone https://github.com/bhilburn/powerlevel9k.git $ZSH_ROOT/custom/themes/powerlevel9k
    else
    	echo "- powerlevel9k already installed"
    fi

fi

printf "\nDecrypting files...\n"
yadm decrypt

printf "\nUpdating the yadm repo origin URL\n"
yadm remote set-url origin "thiosin:thiosin/dotfiles.git"

cd $ORIGINAL_WORKING_DIR

printf "\n=== Finished bootstrap ===\n"
